IAM EOF to Data Block
StratusGrid/terraform-aws-iam-group-restricted-read-only pull request #2
Opened 2022-06-21 20:52 UTC by wesleykirklandsg

IAM EOF to Data Block

2022-06-29 15:22 UTC, rchildress87 requested changes

2022-06-29 15:22 UTC, rchildress87 commented on iamdata.tf
> +      test     = "BoolIfExists"
Think you want `bool` here
https://github.com/StratusGrid/terraform-aws-iam-group-restricted-admin/pull/2

2022-06-29 15:22 UTC, rchildress87 commented on iamdata.tf
> +      "${aws_iam_role.this.arn}"
Interpolation-only syntax

2022-06-29 15:53 UTC, wesleykirklandsg commented on iamdata.tf
> +    actions = [
Resolved in 6ffc288

2022-06-29 15:53 UTC, wesleykirklandsg commented on iamdata.tf
> +      "${aws_iam_role.this.arn}"
Corrected under ca22c5f

2022-08-01 17:32 UTC, rchildress87 commented on iamdata.tf
> +      test     = "BoolIfExists"
I think one of the bool example under Alternative Combinations should be considered as better option but, according to above documentation, this does emulate the policy that is created when you use the IAM visual editor and choose MFA Required. It also matches the policy that this data source is replacing. I'll approve.

2022-08-01 17:32 UTC, rchildress87 approved these changes

2022-08-01 18:19 UTC, merged